/**
 * DropMail disposable email provider.
 *
 * Uses the DropMail public REST API — no auth required.
 * Rate limit: 100 requests/minute per IP (~1.5 s between requests is safe).
 *
 * API:
 *   POST /api/v1/public/mailbox           → { address }
 *   GET  /api/v1/public/mailbox/{address} → { messages: [{ id, from, subject, text, html }] }
 */
import logger from "../../logger.js";
import {
  makeApi,
  makeGetReader,
  createProviderMethods,
} from "./base/apiProvider.js";

// ── Config ────────────────────────────────────────────────────────────────────

const BASE_URL = "https://dropmail.click/api/v1/public";
const TAG = "DropMail";

// ── Helpers ───────────────────────────────────────────────────────────────────

const api = makeApi(BASE_URL);

// Builds the inbox reader used by pollApi.
// DropMail returns full message content in the list response, so we cache it
// and avoid a second HTTP request when reading individual messages.
function buildReader(address) {
  let cache = [];

  return {
    // Fetches all messages for this mailbox and caches them for readMessage.
    async fetchMessages() {
      const data = await api(`/mailbox/${encodeURIComponent(address)}`);
      cache = data?.messages ?? [];
      return cache.map((msg) => ({
        id: msg.id,
        preview: [msg.from ?? "", msg.subject ?? ""].join(" ").trim(),
      }));
    },

    // Returns the full message body from cache — no extra HTTP request needed.
    async readMessage(id) {
      const msg = cache.find((m) => m.id === id);
      return msg ? `${msg.text ?? ""}\n${msg.html ?? ""}` : "";
    },
  };
}

// Reads the mailbox address stored on `page` by createEmail and returns the inbox reader.
const getReader = makeGetReader("_dropmailAddress", TAG, buildReader);

// ── Provider ──────────────────────────────────────────────────────────────────

export default {
  meta: {
    id: "dropmail",
    name: "DropMail",
    url: "https://dropmail.click",
    description: "Disposable temporary email via DropMail public API",
    apiOnly: true,
  },

  // Creates a new DropMail mailbox and stores the address on the page stub.
  async createEmail(page) {
    logger.info(`[${TAG}] Creating mailbox...`);
    const data = await api("/mailbox", { method: "POST" });
    const address = data?.address;
    if (!address) throw new Error(`[${TAG}] No address returned from API.`);
    page._dropmailAddress = address;
    logger.info(`[${TAG}] Email ready: ${address}`);
    return address;
  },

  // Shared polling methods — generated by the factory.
  ...createProviderMethods(TAG, getReader),
};
