/**
 * Mail.tm disposable email provider.
 *
 * Uses the Mail.tm REST API (https://api.mail.tm) instead of browser automation.
 * Inbox polling is done via pollApi() — no Playwright page needed.
 */
import logger from "../../logger.js";
import { generateUsername, generatePassword } from "../utils/generators.js";
import { makeApi, createProviderMethods } from "./base/apiProvider.js";

// ── Config ────────────────────────────────────────────────────────────────────

const BASE_URL = "https://api.mail.tm";

// ── Helpers ───────────────────────────────────────────────────────────────────

const api = makeApi(BASE_URL);

// Builds the inbox reader used by pollApi — fetches message list and reads individual messages.
function buildReader(token) {
  return {
    // Fetches the first page of messages and returns lightweight preview objects.
    async fetchMessages() {
      const data = await api("/messages?page=1", { token });
      return (data["hydra:member"] ?? []).map((msg) => ({
        id: msg.id,
        preview: [
          msg.from?.name ?? "",
          msg.from?.address ?? "",
          msg.subject ?? "",
          msg.intro ?? "",
        ]
          .join(" ")
          .trim(),
      }));
    },

    // Fetches the full message body by ID and joins text + HTML parts into one string.
    async readMessage(id) {
      const full = await api(`/messages/${id}`, { token });
      const htmlParts = Array.isArray(full.html)
        ? full.html.join("\n")
        : (full.html ?? "");
      return `${full.text ?? ""}\n${htmlParts}`;
    },
  };
}

// Reads the auth token stored on `page` by createEmail and returns the inbox reader.
function getReader(page) {
  const token = page._mailtmToken;
  if (!token)
    throw new Error("[MailTm] No auth token — call createEmail first.");
  return buildReader(token);
}

// ── Provider ──────────────────────────────────────────────────────────────────

export default {
  meta: {
    id: "mailtm",
    name: "Mail.tm",
    url: BASE_URL,
    description: "Disposable temporary email via Mail.tm API",
    apiOnly: true,
  },

  // Creates a Mail.tm account, obtains an auth token, and stores both on the page stub.
  async createEmail(page) {
    logger.info("[MailTm] Fetching available domains...");
    const domainsData = await api("/domains?page=1");
    const domains = domainsData["hydra:member"] ?? [];
    if (!domains.length) throw new Error("[MailTm] No domains available.");

    const domain = domains[0].domain;
    const address = `${generateUsername()}@${domain}`;
    const password = generatePassword();

    logger.info(`[MailTm] Creating account: ${address}`);
    await api("/accounts", { method: "POST", body: { address, password } });

    logger.info("[MailTm] Requesting auth token...");
    const { token } = await api("/token", {
      method: "POST",
      body: { address, password },
    });

    // Store credentials on the page stub so polling methods can read them later.
    page._mailtmToken = token;
    page._mailtmAddress = address;

    logger.info(`[MailTm] Email ready: ${address}`);
    return address;
  },

  // Shared polling methods — generated by the factory.
  ...createProviderMethods("MailTm", getReader),
};
